import { StyleSheet } from "react-native";
import colors from "../../styles/colors";

 export const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: colors.background },
  scrollContent: { paddingHorizontal: 20, paddingBottom: 20 },

  greetingRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start',paddingHorizontal:18,paddingVertical:12 },
  greetingText: { fontSize: 14, color: colors.textSecondary },
  greetingTitle: { fontSize: 24, fontWeight: '800', color: colors.text, marginTop: 4 },
  avatar: { width: 48, height: 48, borderRadius: 24 },

  searchRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 14,
    paddingHorizontal: 14,
    height: 52,
    marginTop: 20,
  },
  searchIcon: { fontSize: 15, marginRight: 10, color: colors.textMuted },
  searchInput: { flex: 1, fontSize: 14, color: colors.text },
  filterIcon: { fontSize: 16 },

  sectionHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginTop: 28,
    marginBottom: 14,
  },
  sectionTitle: { fontSize: 19, fontWeight: '800', color: colors.text },
  sectionSubtitle: { fontSize: 13, color: colors.textSecondary, marginTop: 4 },
  viewAll: { fontSize: 14, fontWeight: '700', color: colors.primary },

  // Featured card
  featuredCard: {
    borderRadius: 20,
    borderWidth: 1,
    borderColor: colors.border,
    overflow: 'hidden',
    backgroundColor: colors.white,
  },
  featuredBanner: { padding: 18, minHeight: 18, justifyContent: 'space-between' },
  featuredTopRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start' },
  tagsRow: { flexDirection: 'row', gap: 8 },
  bannerTagChip: {
    backgroundColor: 'rgba(255,255,255,0.9)',
    borderRadius: 14,
    paddingVertical: 5,
    paddingHorizontal: 12,
    marginRight: 8,
  },
  bannerTagText: { fontSize: 12, fontWeight: '700', color: colors.primaryDark },
  timeLeftPill: {
    backgroundColor: 'rgba(255,255,255,0.9)',
    borderRadius: 14,
    paddingVertical: 5,
    paddingHorizontal: 12,
  },
  timeLeftText: { fontSize: 12, fontWeight: '700', color: colors.primaryDark },
  taglineRow: { flexDirection: 'row', alignItems: 'center', marginTop: 24 },
  taglineIcon: { fontSize: 18, marginRight: 10, color: colors.white },
  taglineText: { fontSize: 19, fontWeight: '800', color: colors.white },

  featuredBody: { padding: 18 },
  featuredTitleRow: { justifyContent: 'space-between', alignItems: 'flex-start',gap:8 },
  featuredTitle: { fontSize: 20, fontWeight: '800', color: colors.text, flex: 1, marginRight: 8 },
  registeredPill: { backgroundColor: colors.primaryLight, borderRadius: 14, paddingVertical: 6, paddingHorizontal: 12 },
  registeredPillText: { fontSize: 12, fontWeight: '700', color: colors.primaryDark },
  featuredSubtitle: { fontSize: 13, color: colors.textSecondary, marginTop: 6 },

  priceRow: { flexDirection: 'row', gap: 48, marginTop: 20 },
  priceLabel: { fontSize: 13, color: colors.textSecondary, marginBottom: 4 },
  priceValue: { fontSize: 22, fontWeight: '800', color: colors.primaryDark },
  priceValueDark: { fontSize: 22, fontWeight: '800', color: colors.text },

  spotsRow: { flexDirection: 'row', justifyContent: 'space-between', marginTop: 20 },
  spotsLeftText: { fontSize: 14, fontWeight: '700', color: colors.primaryDark },
  bookedText: { fontSize: 13, color: colors.textSecondary },
  progressTrack: {
    height: 6,
    backgroundColor: colors.primaryLight,
    borderRadius: 3,
    marginTop: 8,
    overflow: 'hidden',
  },
  progressFill: { height: '100%', backgroundColor: colors.primary, borderRadius: 3 },

  joinButton: {
    backgroundColor: colors.primaryDark,
    borderRadius: 14,
    paddingVertical: 15,
    alignItems: 'center',
    marginTop: 18,
  },
  joinButtonText: { color: colors.white, fontSize: 15, fontWeight: '700' },

  // List items
  listItem: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 16,
    padding: 16,
    marginBottom: 14,
    backgroundColor: colors.white,
  },
  listItemIconBox: {
    width: 48,
    height: 48,
    borderRadius: 12,
    backgroundColor: colors.primaryLight,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 14,
  },
  listItemIcon: { fontSize: 20, color: colors.primaryDark },
  listItemTopRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start' },
  listItemTitle: { fontSize: 16, fontWeight: '700', color: colors.text, flex: 1, marginRight: 8 },
  listItemTime: { fontSize: 13, fontWeight: '700', color: colors.primaryDark },
  listItemTimeUrgent: { color: colors.danger },
  listItemMeta: { fontSize: 13, color: colors.textSecondary, marginTop: 4 },
  listProgressTrack: {
    height: 5,
    backgroundColor: colors.primaryLight,
    borderRadius: 3,
    marginTop: 10,
    overflow: 'hidden',
  },
  listProgressFill: { height: '100%', backgroundColor: colors.primary, borderRadius: 3 },

  // Bottom tab bar
  tabBar: {
    flexDirection: 'row',
    borderTopWidth: 1,
    borderTopColor: colors.border,
    backgroundColor: colors.white,
    paddingVertical: 10,
    paddingBottom: 18,
  },
  tabItem: { flex: 1, alignItems: 'center' },
  tabIcon: { fontSize: 18, color: colors.textMuted },
  tabIconActive: { color: colors.primary },
  tabLabel: { fontSize: 11, color: colors.textMuted, marginTop: 4 },
  tabLabelActive: { color: colors.primary, fontWeight: '700' },
});